### ISSUE TITLE
running antlrworks 2.1 on windows 7

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/antlrworks2#17]
**Anonymous** created an issue 2013-12-11

> After downloading and unzipping 2.1 version (http://tunnelvisionlabs.com/downloads/antlr/2013-07-21-antlrworks-2.1.zip) I try to run it.
> 
> In response I get the following waring: Warning - could not install some modules: org.apache.commons.io - org.netbeans.InvalidException: Netigso: D:\playground\2013-07-21-antlrworks-2.1\antlrworks2\ide\modules\org-apache-commons-io.jar: Not found bundle:org.apache.commons.io
> 
> I choose the option "diable modules and continue". The application quits.
> 
> I use the following version of Java: C:\Users\karolbr>java -version java version "1.7.0_25" Java(TM) SE Runtime Environment (build 1.7.0_25-b17) Java HotSpot(TM) 64-Bit Server VM (build 23.25-b01, mixed mode)
> 
> I know my operating system is flawed (by definition), but is there any way to run the app?

**Comment by ckuhn203** [comment]
You're the man @frenchtoast747. Worked like a charm. Thank you.

**Comment by AimingHua** [comment]
same problem, @frenchtoast747 thanks

**Comment by fjsr-py** [comment]
In Linux I solved removing .antlrworks2 and .cache with rm -r (directory) two folders are in the /home/(user)/ folder.

**Comment by ooinfo** [comment]
thaks

**Comment by drriguz** [comment]
On mac, it's  /Users/<USER>/Library/Application\ Support/antlrworks2 
[ref](https://groups.google.com/forum/#!topic/antlr-discussion/qvNcE5HR_BA)

**Comment by BIT-Majunda** [comment]
the same problem , thanks @frenchtoast747
