### ISSUE TITLE
Build errors on master

### ISSUE THREAD

**Issue by ziuchkovski** [tunnelvisionlabs/antlrworks2#31]
Hi, it looks like there are some ant build problems with the code from master.  In particular, the tasks under org-antlr-works-editor fail.  The first failure is related to the grammar compilation:

```
antlr4:
     [echo] Generating ANTLR 4 grammars:
     [echo]   org/antlr/works/editor/grammar/experimental/GrammarLexer.g4
     [echo]   org/antlr/works/editor/grammar/experimental/GrammarParser.g4
     [echo]   org/antlr/works/editor/grammar/highlighter/GrammarHighlighterLexer.g4
     [echo]   org/antlr/works/editor/st4/experimental/TemplateLexer.g4
     [echo]   org/antlr/works/editor/st4/experimental/TemplateParser.g4
     [echo]   org/antlr/works/editor/st4/highlighter/GroupHighlighterLexer.g4
     [java] error(7):  cannot find or open file: *.g4
```

I started patching the org-antlr-works-editor build.xml to fix the grammar compilation, but the grammar files look like they are using a new 'abstract' option that isn't available in the compiled antlr4 jars that are retrieved by ant.  So I stopped there, realizing I'm probably missing some pieces of the build process.

Let me know if I can provide any other useful info on my end.

**Comment by transistor1** [comment]
For future reference to anyone who wants to build on Linux... I haven't done Java dev in a while, and I don't know anything about Ant, but I wanted to build AntlrWorks2 on Linux. I was able to hack my way through it; [here](https://gist.github.com/transistor1/694ac03beeb3899933fa) is a patch against commit bfee49a9b029625ef3bffeaa1b026d2bbc95b61d, with the changes I made to the repo to get it to build.
