### ISSUE TITLE
Unable to install AntlrWorks-Plugin for NetBeans 8.0.2

### ISSUE THREAD

**Issue by Quurz** [tunnelvisionlabs/antlrworks2#49]
Hello

First I would thank you guys at TunnelVision for the great work.

Unfotunaltely the plugin seems to be incomaptible with NetBeans 8.0.2. Trying to install it, I'm receiving the following error message:

Some plugins require plugin Editor Settings Storage to be installed.
The plugin Editor Settings Storage is requested in implementation version 201408251540.  The following plugin is affected:       ANTLRWorks Editor 
Some plugins require plugin Editor Options to be installed.
The plugin Editor Options is requested in implementation version 201408251540.  The following plugin is affected:       ANTLRWorks Editor

My NetBeans installation:

Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: NetBeans IDE is updated to version NetBeans 8.0.2 Patch 2
Java: 1.8.0_31; Java HotSpot(TM) 64-Bit Server VM 25.31-b07
Runtime: Java(TM) SE Runtime Environment 1.8.0_31-b13
System: Linux version 3.16.7-21-desktop running on amd64; UTF-8; de_DE (nb)

It would be nice, if you'll find the time to look into this.

Thank you very much!

Best regards

Alex

**Comment by JunielKatarn** [comment]
@Quurz, I have also experienced this. Sam explained that due to NetBeans's dependency model, if some internal module version is changed (in this case, module 'Editor Options'), ANTLRWorks won't be able to load because it expects an exact version number, which is now outdated.

I believe the only solution is to update that dependency version in the ANTLRWorks code, and rebuild.
Please note, I think because of the nature of the ant scripts, it might only build on Windows.

**Comment by sharwell** [comment]
Yes, the dependency model is a nightmare. Even features like highlighting all instances of the current identifier (based on the caret position) require "implementation dependencies".

**Comment by JunielKatarn** [comment]
Sam, at this point I'd like to volunteer to keep such dependencies up to date. At the very least, the 'Editor Options' one.

Can you please point me to the config file which defines that module's required version?

**Comment by sharwell** [comment]
@JunielKatarn @Quurz if either of you is working on a Mac, can you tell me if #50 fixes the build for you?

**Comment by Quurz** [comment]
Hello Sam, Hello Juniel

I'm sorry, no Mac here. I'm using Linux. Is there any possibility for me to help?

**Comment by sharwell** [comment]
@Quurz Yes, I believe linux had the same problem.

**Comment by Quurz** [comment]
It's late here in Germany and I've to work tomorrow. Furthermore I'll be not at home most of the weekend. I'm off to Hannover visiting the german Maker-Faire...   :)
But I'll give it a try, as soon as I'm back.

Thank you!

**Comment by JunielKatarn** [comment]
I'll test Mac OS during the weekend.

On Thursday, June 4, 2015, Sam Harwell <notifications@github.com> wrote:

> @JunielKatarn <https://github.com/JunielKatarn> @Quurz
> <https://github.com/Quurz> if either of you is working on a Mac, can you
> tell me if #50 <https://github.com/tunnelvisionlabs/antlrworks2/pull/50>
> fixes the build for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tunnelvisionlabs/antlrworks2/issues/49#issuecomment-109057534>
> .
>


-- 
- Julio

**Comment by JunielKatarn** [comment]
@sharwell I'm not able to even begin the build process. I do have an external NetBeans harness set up.
Can you please share the guidelines/commands to build?

Thanks!

**Comment by sharwell** [comment]
To build from the command line in Windows, I first run this PowerShell script to set up the environment.

```ps
$env:Path = $env:Path + ';' + 'C:\Program Files\Java\jdk1.7.0_51\bin' + ';' + 'C:\Program Files\NetBeans 8.0.1\extide\ant\bin'
$env:JAVA_HOME = 'C:\Program Files\Java\jdk1.7.0_51'
$env:ANT_OPTS = '-Xms1g -Xmx2g -XX:PermSize=1g -XX:MaxPermSize=2g'
$env:M2_HOME = 'C:\Program Files\NetBeans 8.0.1\java\maven'
```

Then, from within the ANTLRWorks 2 source folder, I run the following to actually build the project:

```
ant clean
ant build
```

**Comment by JunielKatarn** [comment]
Hi again. I guess I'm probably missing something.
Having correctly set the enviroment variables as you pointed above, but for Mac OS X:
```
ant clean
Buildfile: /Volumes/EMPTY/antlrworks/sam/build.xml

download:

BUILD FAILED
/Volumes/EMPTY/antlrworks/sam/build.xml:7: The following error occurred while executing this line:
/Volumes/EMPTY/antlrworks/sam/nbproject/build-impl.xml:42: Cannot find NetBeans build harness.
Check that nbplatform.nb801.netbeans.dest.dir and nbplatform.nb801.harness.dir are defined.
On a developer machine these are normally defined in ${user.properties.file}=${netbeans.user}/build.properties
but for automated builds you should pass these properties to Ant explicitly.
You may instead download the harness and platform: -Dbootstrap.url=.../tasks.jar -Dautoupdate.catalog.url=.../updates.xml

Total time: 0 seconds
```

So, I deduced I need to provide the platform and harness directories. I used my current (stable) NetBeans installations for this purpose:
```
export suite_dir='/Applications/NetBeans/NetBeans 8.0.1.app/Contents/Resources/NetBeans'
export netbeans_dest_dir=${suite_dir}/platform
export harness_dir=${suite_dir}/harness
```

Then, executed:
```
ant -Dnbplatform.nb801.netbeans.dest.dir="$netbeans_dest_dir" -Dnbplatform.nb801.harness.dir="$harness_dir" clean
```
which finished successfully:
```
...
clean:

BUILD SUCCESSFUL
Total time: 1 second
```

However, after trying to build:
```
ant -Dnbplatform.nb801.netbeans.dest.dir="$netbeans_dest_dir" -Dnbplatform.nb801.harness.dir="$harness_dir" build

...
build-init:
    [mkdir] Created dir: /Volumes/EMPTY/antlrworks/sam/build/public-package-jars

BUILD FAILED
/Applications/NetBeans/NetBeans 8.0.1.app/Contents/Resources/NetBeans/harness/suite.xml:187: The following error occurred while executing this line:
/Applications/NetBeans/NetBeans 8.0.1.app/Contents/Resources/NetBeans/harness/build.xml:174: java.io.IOException: Invalid ${cluster.path.final}:
	at org.netbeans.nbbuild.ModuleListParser.<init>(ModuleListParser.java:779)
	at org.netbeans.nbbuild.ParseProjectXml.execute(ParseProjectXml.java:451)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.helper.SingleCheckExecutor.executeTargets(SingleCheckExecutor.java:38)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.taskdefs.Ant.execute(Ant.java:441)
	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:306)
	at org.apache.tools.ant.taskdefs.SubAnt.execute(SubAnt.java:221)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:106)
	at org.apache.tools.ant.Task.perform(Task.java:348)
	at org.apache.tools.ant.Target.execute(Target.java:435)
	at org.apache.tools.ant.Target.performTasks(Target.java:456)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1393)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1364)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1248)
	at org.apache.tools.ant.Main.runBuild(Main.java:851)
	at org.apache.tools.ant.Main.startAnt(Main.java:235)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:280)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:109)

Total time: 0 seconds
```

What kind of NetBeans platform configuration do you use?

**Comment by sharwell** [comment]
I recommend downloading from https://netbeans.org/downloads/ using the following options:

1. For version, select **8.0.2**.
1. For platform, select **OS Independent Zip**.
1. Under **Java SE**, click Download.

Extract the files to a location on your machine which will hold "NetBeans Platforms". Don't run NetBeans from this location, but use it for configuring the NetBeans platform to use for a build.

![image](https://cloud.githubusercontent.com/assets/1408396/8110436/e4d9aa9c-1021-11e5-8902-40fbba3ecd15.png)

**Comment by Quurz** [comment]
Hello

Sorry, I was buried in work this week...   =(

I've to admit, that I'm very unfamiliar with git. Could please somebody explain to me, how to download the build file? Yes, I know that's really embarrassing but please don't make fun of me...

As soon I was able to fetch the file, I'll try to make a build.

Best regards

Alex

**Comment by sharwell** [comment]
Hi Alex,

It's no problem. What operating system do you have? I'm not the best at explaining how to use Git, but I'm sure I could find someone who can help.

If you don't want to use Git, you can simply download a Zip file containing all the source from the repository. This will let you build the project, but won't let you send your changes back to us for review. It's the highlighted button here:

![image](https://cloud.githubusercontent.com/assets/1408396/8144911/f18c0202-11b7-11e5-890b-05cbbc67aca8.png)

**Comment by Quurz** [comment]
Hello Sam

Thank's for the swift reply and the help...   :)
I'm working with a linux system and just have downloaded and unzipped
the file. I'm now about to start the build.

I'll be back at you, the moment I got the results.


Best regards

Alex

Am 13.06.2015 um 17:36 schrieb Sam Harwell:

**Comment by Quurz** [comment]
Hello Sam

Sorry, it took me some time...But at last I've some results...
Unfortunately, these results aren't looking this good...

While building, this error was thrown:

Generating ANTLR 4 grammars:
  org/antlr/works/editor/grammar/experimental/GrammarLexer.g4
  org/antlr/works/editor/grammar/experimental/GrammarParser.g4
  org/antlr/works/editor/grammar/highlighter/GrammarHighlighterLexer.g4
  org/antlr/works/editor/st4/experimental/TemplateLexer.g4
  org/antlr/works/editor/st4/experimental/TemplateParser.g4
  org/antlr/works/editor/st4/highlighter/GroupHighlighterLexer.g4
error(7):  cannot find or open file: *.g4
error(7):  cannot find or open file: *.g4
error(7):  cannot find or open file: *.g4
error(7):  cannot find or open file: *.g4
/home/Alexander/Spielwiese/ntebans_harness/suite.xml:187: The following
error occurred while executing this line:
/home/Alexander/Spielwiese/ANTLRWorksPlugin/antlrworks2-bfee49a9b029625ef3bffeaa1b026d2bbc95b61d/org-antlr-works-editor/build.xml:120:
The following error occurred while executing this line:
/home/Alexander/Spielwiese/ANTLRWorksPlugin/antlrworks2-bfee49a9b029625ef3bffeaa1b026d2bbc95b61d/org-antlr-works-editor/build.xml:95:
Java returned: 1
BUILD FAILED (total time: 24 seconds)

I'll try to figure this out...

Best regards

Alex

Am 13.06.2015 um 17:36 schrieb Sam Harwell:

**Comment by sharwell** [comment]
Hi @Quurz,

No need to apologize. If you join me in the [Gitter room](https://gitter.im/tunnelvisionlabs/antlrworks2) I'll help you out. :+1:

**Comment by Quurz** [comment]
Hello Sam

I've fallen asleep...   =(
And now it's 23:44 pm here in germany...
Could we give it a try tomorrow?


Best regards

Alex



Am 13.06.2015 um 20:24 schrieb Sam Harwell:

**Comment by sharwell** [comment]
Works for me :smile:

**Comment by Quurz** [comment]
Thanks :)

Then I'll go to bed now...


Best regards 

Alex 


Von Samsung Mobile gesendet

<div>-------- Ursprüngliche Nachricht --------</div><div>Von: Sam Harwell <notifications@github.com> </div><div>Datum:13.06.2015  23:47  (GMT+01:00) </div><div>An: tunnelvisionlabs/antlrworks2 <antlrworks2@noreply.github.com> </div><div>Cc: Alexander Schell <Alex.W.Schell@web.de> </div><div>Betreff: Re: [antlrworks2] Unable to install AntlrWorks-Plugin for NetBeans
  8.0.2 (#49) </div><div>
</div>Works for me

**Comment by Chris2011** [comment]
Is there any updated nbm file for Netbeans 8.0.2 or 8.1? Please provide it and not holding only for your self. Please read my last comment here for what I mean: #55.

Thx.

**Comment by paulcadman** [comment]
For future reference I built the plugin with a netbeans 8.0.2 installation on linux with:
```
$ export SUITE_DIR=/path/to/netbeans-8.0.2
$ export NETBEANS_DEST_DIR=$SUITE_DIR
$ export HARNESS_DIR=$SUITE_DIR/harness
$ ant -Dnbplatform.nb802.netbeans.dest.dir=$NETBEANS_DEST_DIR -Dnbplatform.nb802.harness.dir=$HARNESS_DIR nbms
```
To install the plugin in netbeans
* Select Tools>Plugins
* In the Downloaded tab click 'Add Plugins'
* Navigate to `build/updates` within the Antlrworks project you've just built
* Select all `.nbm` files
* Follow the prompts to install the plugin

**Comment by Chris2011** [comment]
Still not possible for Netbeans 8.1.

**Comment by NotNormal** [comment]
Broken again in Netbeans 8.2:
Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: NetBeans IDE is updated to version NetBeans 8.2 Patch 1
Java: 1.8.0_131; Java HotSpot(TM) 64-Bit Server VM 25.131-b11
Runtime: Java(TM) SE Runtime Environment 1.8.0_131-b11
System: Mac OS X version 10.12.4 running on x86_64; UTF-8; en_US (nb)

**Comment by coreleon** [comment]
> To build from the command line in Windows, I first run this PowerShell script to set up the environment.
> 
> ```postscript
> $env:Path = $env:Path + ';' + 'C:\Program Files\Java\jdk1.7.0_51\bin' + ';' + 'C:\Program Files\NetBeans 8.0.1\extide\ant\bin'
> $env:JAVA_HOME = 'C:\Program Files\Java\jdk1.7.0_51'
> $env:ANT_OPTS = '-Xms1g -Xmx2g -XX:PermSize=1g -XX:MaxPermSize=2g'
> ```
> 
> Then, from within the ANTLRWorks 2 source folder, I run the following to actually build the project:
> 
> ```
> ant clean
> ant build
> ```

Some developers like you (that have no robust knowledge in Programming (and computer science in general)) are time wasters for other developers.
I have great knowledge on Netbeans platform and i know what is the solution. But i will leave it to you to find it out (because YOU ARE the developer (meaning THAT IT IS YOU the one who SHOULD HAVE a good knowledge of the platform that you have chosen to build "some products" against).
If you don't know how the Netbeans platform build process works DO NOT waste peoples lives.

**Comment by Chris2011** [comment]
@coreleon can you please stop being rude, disrespectful and disgusting? Thank you.

**Comment by coreleon** [comment]
@Chris2011  go cut you beard!
