### ISSUE TITLE
Different with antlrworks and antlrworks2

### ISSUE THREAD

**Issue by feb21** [tunnelvisionlabs/antlrworks2#62]
Hello!

Issue in the title.

**Comment by sharwell** [comment]
Yes, antlrworks and antlrworks 2 are totally different projects. They don't share any code at all.

**Comment by feb21** [comment]
@sharwell It can make a table of differences?

**Comment by sharwell** [comment]
@feb21 I wasn't an author on ANTLRWorks and didn't reference it when creating ANTLRWorks 2. Literally everything is different since I totally started over from nothing.
